# Generated by Django 3.2.12 on 2022-08-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
