# Generated by Django 3.2.12 on 2022-08-02 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_pk', models.AutoField(primary_key=True, serialize=False)),
                ('story_title', models.CharField(max_length=50)),
                ('story_picture', models.ImageField(blank=True, null=True, upload_to='user/story/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('user_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
