# Generated by Django 3.2.12 on 2022-08-02 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_picture',
            field=models.ImageField(default=1, upload_to='user/story/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('hashtag_pk', models.AutoField(primary_key=True, serialize=False)),
                ('hashtag_content', models.CharField(max_length=20)),
                ('story_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story')),
                ('user_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
