# Generated by Django 3.2.12 on 2022-08-03 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0003_auto_20220803_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='like',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
