# Generated by Django 3.2.12 on 2022-08-03 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0004_story_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='like',
        ),
        migrations.AddField(
            model_name='story',
            name='like_user',
            field=models.ManyToManyField(related_name='like_story', to=settings.AUTH_USER_MODEL),
        ),
    ]
