# Generated by Django 3.2.12 on 2022-08-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20220803_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_picture',
            field=models.ImageField(blank=True, default='media/crew/image/프로필기본.png', null=True, upload_to='user/story/'),
        ),
    ]
