# Generated by Django 3.2.12 on 2022-08-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_story_story_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_picture',
            field=models.ImageField(default=1, upload_to='user/story/'),
            preserve_default=False,
        ),
    ]
