# Generated by Django 3.2.12 on 2022-08-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/user/profile/프로필기본.png', null=True, upload_to='user/profile/'),
        ),
    ]
