# Generated by Django 3.2.12 on 2022-08-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='black_reson',
            new_name='black_reason',
        ),
    ]
