# Generated by Django 3.2.12 on 2022-08-04 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew_pk', models.AutoField(primary_key=True, serialize=False)),
                ('is_business', models.BooleanField()),
                ('crew_name', models.CharField(max_length=50, unique=True)),
                ('crew_img', models.ImageField(upload_to='crew/image')),
                ('crew_explain', models.TextField()),
                ('crew_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
