# Generated by Django 3.2.12 on 2022-08-04 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='crew_member',
            field=models.ManyToManyField(blank=True, related_name='crews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crew',
            name='crew_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
