# Generated by Django 3.2.12 on 2022-08-08 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_leader_accept', models.BooleanField()),
                ('user_accept', models.BooleanField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.crew')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
