# Generated by Django 3.2.12 on 2022-08-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0002_auto_20220804_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='crew_region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='crew_img',
            field=models.ImageField(blank=True, default='media/crew/image/프로필기본.png', null=True, upload_to='crew/image'),
        ),
    ]
