# Generated by Django 3.2.12 on 2022-08-08 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crews', '0002_crewinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewSchedule',
            fields=[
                ('crew_schedule_pk', models.AutoField(primary_key=True, serialize=False)),
                ('crew_day', models.DateField()),
                ('color', models.CharField(max_length=20)),
                ('crew_starthour', models.TimeField()),
                ('crew_endhour', models.TimeField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.crew')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
