# Generated by Django 3.2.12 on 2022-08-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0003_auto_20220804_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='crew_img',
            field=models.ImageField(blank=True, default='media/crew/image/상점기본.png', null=True, upload_to='crew/image'),
        ),
    ]
