# Generated by Django 3.2.12 on 2022-08-04 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crews', '0004_alter_crew_crew_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew_article_pk', models.AutoField(primary_key=True, serialize=False)),
                ('crew_title', models.CharField(max_length=50)),
                ('crew_content', models.TextField()),
                ('crew_private', models.BooleanField(default=False)),
                ('crew_pin', models.BooleanField(default=False)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.crew')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrewArticleImage',
            fields=[
                ('article_image_pk', models.AutoField(primary_key=True, serialize=False)),
                ('article_picture', models.ImageField(upload_to='crew_article/image')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.crewarticle')),
            ],
        ),
        migrations.CreateModel(
            name='CrewArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.crewarticle')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
