# Generated by Django 3.2.12 on 2022-08-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='job_main_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
