# Generated by Django 3.2.12 on 2022-08-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_pk',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
