# Generated by Django 3.2.12 on 2022-08-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='oneline_review',
            field=models.TextField(null=True),
        ),
    ]
