# Generated by Django 3.2.12 on 2022-08-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='chosen_button',
        ),
        migrations.AddField(
            model_name='review',
            name='chosen_button',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ButtonReview',
        ),
    ]
