# Generated by Django 3.2.12 on 2022-08-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='chosen_button',
        ),
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.store'),
        ),
        migrations.AddField(
            model_name='review',
            name='chosen_button',
            field=models.ManyToManyField(blank=True, related_name='review', to='reviews.ButtonReview'),
        ),
    ]
