# Generated by Django 3.2.12 on 2022-08-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220802_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonreview',
            name='store',
            field=models.ManyToManyField(blank=True, related_name='button', to='reviews.Store'),
        ),
    ]
