# Generated by Django 3.2.12 on 2022-08-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_buttonreview_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttonreview',
            name='store',
        ),
        migrations.RemoveField(
            model_name='review',
            name='chosen_button',
        ),
        migrations.CreateModel(
            name='StoreButtonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.buttonreview')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.store')),
            ],
        ),
    ]
