# Generated by Django 3.2.12 on 2022-08-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220803_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, default='media/store/logo/상점기본.png', null=True, upload_to='store/logo'),
        ),
    ]
